/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Analizador.AnalizadorDML;
import Analizador.ConectorSingleton;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
/**
 *
 * @author PC-24
 */
public class EditorSQL extends javax.swing.JFrame {
    
    int tam = 12;
    Font fuente;
    AnalizadorDML analizadorDML;
    public EditorSQL() {
        initComponents();
        
        analizadorDML = new AnalizadorDML(); 
        fuente = new Font(Font.MONOSPACED, Font.PLAIN, tam);
        
        this.txtPanel2.setEditable(false);
        
        this.txtPanel1.setFont(fuente);
        this.txtPanel2.setFont(fuente);
        
        NumeroLinea num1 = new NumeroLinea(txtPanel1);
        NumeroLinea num2 = new NumeroLinea(txtPanel2);
        
        jScrollPane2.setRowHeaderView( num1 );
        jScrollPane3.setRowHeaderView( num2 );
        //ImageIcon icon =  new ImageIcon(getClass().getResource());
        
        this.jSplitPane1.setDividerLocation(0.7);
        
        ImageIcon ic_borrar     = new ImageIcon("imagenes/ic_borrar.png");
        ImageIcon ic_alejar     = new ImageIcon("imagenes/ic_alejar.png");
        ImageIcon ic_aumentar   = new ImageIcon("imagenes/ic_aumentar.png");
        ImageIcon ic_comprobar  = new ImageIcon("imagenes/ic_comprobar.png");
        ImageIcon ic_correr     = new ImageIcon("imagenes/ic_correr.png");
        ImageIcon ic_config     = new ImageIcon("imagenes/ic_config.png");
        
        btnBorrar.setIcon(resizeIcon(ic_borrar,btnBorrar));
        btnAlejar.setIcon(resizeIcon(ic_alejar,btnAlejar));
        btnAcercar.setIcon(resizeIcon(ic_aumentar,btnAcercar));
        btnVerificar.setIcon(resizeIcon(ic_comprobar,btnVerificar));
        btnEjecutar.setIcon(resizeIcon(ic_correr,btnEjecutar));
        btnConfigurar.setIcon(resizeIcon(ic_config,btnConfigurar));
        
    }
    
    
    private static Icon resizeIcon(ImageIcon ic,JButton btn) {
        Image img = ic.getImage() ; 
        Image resizedImage = img.getScaledInstance(btn.getWidth(),btn.getHeight(),java.awt.Image.SCALE_SMOOTH);  
        return new ImageIcon(resizedImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBorrar = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        btnAcercar = new javax.swing.JButton();
        btnAlejar = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPanel1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPanel2 = new javax.swing.JTextPane();
        btnEjecutar = new javax.swing.JButton();
        btnConfigurar = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnAcercar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercarActionPerformed(evt);
            }
        });

        btnAlejar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlejarActionPerformed(evt);
            }
        });

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane2.setViewportView(txtPanel1);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jScrollPane3.setViewportView(txtPanel2);

        jSplitPane1.setRightComponent(jScrollPane3);

        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        btnConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarActionPerformed(evt);
            }
        });

        lblEstado.setText("Desconectado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSplitPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAcercar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlejar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 469, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnVerificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnAcercar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnAlejar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnConfigurar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txtPanel1.setText("");
        txtPanel2.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        if (txtPanel1.getText().length() > 0) {
           
            analizadorDML.escribir("dmlIn.txt", txtPanel1.getText());
            txtPanel2.setText(analizadorDML.procesar());
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnAcercarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercarActionPerformed
        // TODO add your handling code here:
        if(tam<34){
            tam++;
            fuente = new Font(Font.MONOSPACED, Font.PLAIN, tam);
            this.txtPanel1.setFont(fuente);
            this.txtPanel2.setFont(fuente);
        }
    }//GEN-LAST:event_btnAcercarActionPerformed

    private void btnAlejarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlejarActionPerformed
        // TODO add your handling code here:
        if(tam>12){
            tam--;
            fuente = new Font(Font.MONOSPACED, Font.PLAIN, tam);
            this.txtPanel1.setFont(fuente);
            this.txtPanel2.setFont(fuente);
        }
    }//GEN-LAST:event_btnAlejarActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
        this.txtPanel2.setText( ConectorSingleton.getInstance().enviarComandos(txtPanel1.getText()));
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void btnConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarActionPerformed
        // TODO add your handling code here:
        ConfiguracionDialog dialogo = new ConfiguracionDialog(this,true);
        dialogo.setVisible(true);
        dialogo.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                lblEstado.setText(ConectorSingleton.getInstance().estado);
            }
        });
    }//GEN-LAST:event_btnConfigurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorSQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercar;
    private javax.swing.JButton btnAlejar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfigurar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTextPane txtPanel1;
    private javax.swing.JTextPane txtPanel2;
    // End of variables declaration//GEN-END:variables
}
